### ISSUE TITLE
Сабменю не скрывается при скроллинге

### ISSUE THREAD

**Issue by winsento** [winsento/skyeer#6]
1. Наводим мышку на "Отрасли" - отображается сабменю.
2. Мышку не уводим скролим вниз. 

![image](https://cloud.githubusercontent.com/assets/2316328/24969549/d297a42a-1fb9-11e7-9c33-721ea24136e7.png)

**Comment by winsento** [comment]
Давай еще показывать/скрывать сабменю по клику (сейчас при наведении). А то странно на мобилках работает.

При скроллинге чекаем если сабменю отображено - скрываем.

**Comment by winsento** [comment]
Еще на мобилках (в горизонтальной ориентации )список в сабменю отображается по три элемента и вылезает справа.
![screenshot_20170412-221458](https://cloud.githubusercontent.com/assets/2316328/24975396/296b7506-1fce-11e7-9f33-d9d3765fd1ad.png)

**Comment by ivan-hilckov** [comment]
Пофиксил. 
На десктопе при скроле меню убираеться. 

>> Давай еще показывать/скрывать сабменю по клику (сейчас при наведении). А то странно на мобилках работает.

Смотри как я понимаю нам не нужно делать показ меню по клику для мобилок ибо для них у нас отдельное меню которое и так показывается по клику. Надо было сделать так что бы для портретного представления тоже включался режим мобилки. 

Собственно теперь включается. 

Ну и был баг что если меню не влазит то не возможно добраться до нижних пунктов намутил скрол если меню больше чем экран мбоилки.
